### ISSUE TITLE
make: *** No rule to make target 'all'.  Stop.

### ISSUE THREAD

**Issue by lbhuang3s** [octantbio/octopus#1]
Hi, I am trying to run octopus on Docker with my Mac. I follow the instructions from "Running the Analysis Pipeline", and when I am at the step: 

cd octopus
make all

I got the following error message:

root@e460de0fed33:~/octopus# make all
make: *** No rule to make target 'all'.  Stop.

How can I fix this problem?

**Comment by nlarusstone** [comment]
Hi @lbhuang3s,

Sorry for the late reply. Can you confirm that you have `Makefile` in your current directory (e.g. by running `ls`)? 

Thanks!

**Comment by nlarusstone** [comment]
Closing as not reproducible -- feel free to reopen with more details
