### ISSUE TITLE
make error in preprocessing

### ISSUE THREAD

**Issue by rekham1077** [octantbio/octopus#2]
Hello, I am trying to run octopus using docker and I get an error at one of the preprocessing steps.

See error below:

Preprocessing plates in pipeline/20210625_iseqrun8
Makefile:96: recipe for target 'pipeline/20210625_iseqrun8/preproc' failed
make: *** [pipeline/20210625_iseqrun8/preproc] Error 255

I'm not entirely sure how to troubleshoot this error, any help would be appreciated. thanks! 

edit: if I try to restart it I get this error message:
root@174d49211422:~/octopus# make -k all
Preprocessing plates in pipeline/20210625_iseqrun8
Makefile:96: recipe for target 'pipeline/20210625_iseqrun8/preproc' failed
make: *** [pipeline/20210625_iseqrun8/preproc] Error 29
Sanitizing input fastas
Flattening pipeline/20210625_iseqrun8/input.fasta
Splitting pipeline/20210625_iseqrun8/input-refs.fasta into individual fastas
Splitting input library into tsv
make: Target 'all' not remade because of errors.

**Comment by rekham1077** [comment]
update: it appears to be a memory issue. if I increase memory allocation in my docker preferences and I subsample the input fastq files then I get past the pre-process step

Now it crashes out at variant calling:
root@8f928414abb3:~/octopus# make -k all
Calling variants for all plates in pipeline/20210625_iseqrun8
Makefile:241: recipe for target 'pipeline/20210625_iseqrun8/guided' failed
make: *** [pipeline/20210625_iseqrun8/guided] Error 8
Splitting input library into tsv
make: Target 'all' not remade because of errors.

I am using macOS Catalina, I have 2.6 GHz 6-core intel core i7 w/ 16 GB memory. I tried increasing cpus and mem in docker desktop preferences but have not got it past this step at any setting. Will it be possible to use my current set up or do I need something better?

What is strange is that the docker memory monitor does not appear to be using the entire allocation

**Comment by nlarusstone** [comment]
Hi @rekham1077, if you look at our wiki (https://github.com/octantbio/octopus/wiki/Installation#hardware), we suggest running on a machine with at least 32 GB of RAM and 16 cores. The type of processing OCTOPUS does is intended to be done on a server rather than a laptop.

That being said, we've been able to run it (albeit slowly) on laptops with no more than 8 cores and 8GB of RAM.

It's hard to debug your issue (which could be data related) without any more error messages. Can you try running the `variant-calling.sh` script on its own with the correct arguments and upload what the error message is here?

**Comment by rekham1077** [comment]
Okay, I looked at the guided err logs and this is what it says:

root@dbc7c4abdeb0:~/octopus/pipeline/20210625_iseqrun8/sub# cat A01-A01-CGTACGTA.guided.err
java -ea -Xmx32g -cp /usr/local/bbmap/current/ align2.BBMap build=1 overwrite=true fastareadlen=500 -Xmx32g threads=1 -eoom in=pipeline/20210625_iseqrun8/sub/A01-A01-CGTACGTA.ecc.fq.gz ref=pipeline/20210625_iseqrun8/lib/input_pR496_=_temP131_=_eBA001_pTDH3-Bc_GapN.fasta outm=stdout.sam nodisk overwrite maxindel=2000
Exception in thread "main" java.lang.AssertionError: Invalid input file: 'pipeline/20210625_iseqrun8/lib/input_pR496_'
	at align2.AbstractMapper.preparse0(AbstractMapper.java:828)
	at align2.AbstractMapper.<init>(AbstractMapper.java:53)
	at align2.BBMap.<init>(BBMap.java:43)
	at align2.BBMap.main(BBMap.java:31)

looking at the file seems normal: ( i just pasted the first few lines below)
(base) rekhamurali@Rekhas-MacBook-Pro lib % cat input_pR496_=_temP131_=_eBA001_pTDH3-Bc_GapN.fasta
>input_pR496_=_temP131_=_eBA001_pTDH3-Bc_GapN
TCATGACCAAAATCCCTTAACGTGAGTTTTCGTTCCACTGAGCGTCAGACCCCGTAGAAAAGATCAAAGGATCTTCTTGAGATCCTTTTTTTCTGCGCGTAATCTG

It seems like it might be cutting off the name for some reason?

**Comment by rekham1077** [comment]
I ended up fixing it by truncating my sequence names to be smaller than 11 characters, and now:

root@54e540926420:~/octopus# make -k all
Demultiplexing pipeline/20210625_iseqrun8
Preprocessing plates in pipeline/20210625_iseqrun8
Calculating well statistics for pipeline/20210625_iseqrun8
Sanitizing input fastas
Flattening pipeline/20210625_iseqrun8/input.fasta
De novo assembling all plates in pipeline/20210625_iseqrun8
Aggregating all contigs in pipeline/20210625_iseqrun8
Mapping contigs from pipeline/20210625_iseqrun8
Splitting pipeline/20210625_iseqrun8/input-refs.fasta into individual fastas
Calling variants for all plates in pipeline/20210625_iseqrun8
Parsing variants from FreeBayes for pipeline/20210625_iseqrun8
Calculating percent bases <10x and <3x coverage for pipeline/20210625_iseqrun8
Checking for contaminated barcodes
Splitting input library into tsv
Aggregating everying together into pipeline/20210625_iseqrun8/aggregated-stats.tsv


So it seems like it works! This is still subsampled ( I only processed 1% of reads due to initial memory problems )

**Comment by nlarusstone** [comment]
Great! Going to close this issue -- please let us know if you have any more problems
